#!/usr/bin/env python

from ConfigParser import ConfigParser
from copy import copy
from datetime import datetime, timedelta
from enginewrangler import Wrangler, FileDownload
from enginewrangler.valuetypes import *
from urlparse import urljoin
from optparse import OptionParser
from os import getcwd, makedirs, path

CONFIG_FILENAME = path.join(getcwd(), 'ew.cfg')
OUTPUT_DIR = path.join(getcwd(), 'output')
VARS_FILENAME = path.join(getcwd(), 'vars.json')
EPOCH = datetime(1970, 1, 1, 0, 0, 0)
DEFAULTS = {
    'host': 'localhost',
    'port': 3306,
    'database': '',
    'username': 'mysql',
    'password': 'mysql',
    'prefix': 'exp_',
    'site': 'default_site',
    'format': 'xml',
    'split': False,
    'htmlfields': None,
    'attachments': 'attachments'
}

def main():
    defaults = copy(DEFAULTS)

    if path.exists(CONFIG_FILENAME):
        config = ConfigParser()
        config.read(CONFIG_FILENAME)

        defaults.update(
            dict(
                config.items('Engine Wrangler')
            )
        )

    parser = OptionParser()
    parser.add_option(
        '-o', '--host',
        dest = 'host',
        help = 'MySQL host',
        default = defaults.get('host')
    )

    parser.add_option(
        '-p', '--port',
        dest = 'port',
        type = 'int',
        help = 'MySQL port',
        default = defaults.get('port')
    )

    parser.add_option(
        '-u', '--user',
        dest = 'username',
        help = 'MySQL username',
        default = defaults.get('username')
    )

    parser.add_option(
        '-w', '--password',
        dest = 'password',
        help = 'MySQL password',
        default = defaults.get('password')
    )

    parser.add_option(
        '-d', '--database',
        dest = 'database',
        help = 'MySQL database name',
        default = defaults.get('database')
    )

    parser.add_option(
        '-r', '--prefix',
        dest = 'prefix',
        help = 'ExpressionEngine table prefix',
        default = defaults.get('prefix')
    )

    parser.add_option(
        '-s', '--site',
        dest = 'site',
        help = 'ExpressionEngine site name',
        default = defaults.get('site')
    )

    parser.add_option(
        '-f', '--format',
        dest = 'format',
        help = 'Output file format',
        default = defaults.get('format')
    )

    parser.add_option(
        '-l', '--split',
        dest = 'split_channels',
        help = 'Split output by content type',
        action = 'store_true',
        default = defaults.get('split') in ('true', 'yes', '1', True, 1)
    )

    parser.add_option(
        '-m', '--imgpath',
        dest = 'image_path',
        help = 'Path to store images',
        default = defaults.get('imgpath')
    )

    parser.add_option(
        '-n', '--imgdomain',
        dest = 'image_domain',
        help = 'Domain for images',
        default = defaults.get('imgdomain')
    )

    parser.add_option(
        '--imagepattern',
        dest = 'image_pattern',
        help = 'Replace image URLs using this pattern',
        default = defaults.get('imagepattern')
    )

    parser.add_option(
        '--avatarbase',
        dest = 'avatar_base',
        help = '',
        default = defaults.get('avatarbase')
    )

    parser.add_option(
        '--avatarpath',
        dest = 'avatar_path',
        help = '',
        default = defaults.get('avatarpath')
    )

    parser.add_option(
        '--avatarpattern',
        dest = 'avatar_pattern',
        help = 'Replace avatar URLs using this pattern',
        default = defaults.get('avatarpattern')
    )

    parser.add_option(
        '--htmlfields',
        dest = 'html_fields',
        help = 'Specify HTML fields (channel:field)',
        default = defaults.get('htmlfields')
    )

    parser.add_option(
        '--attachments',
        dest = 'attachments',
        help = 'Name of the key or tag under which to store attachments',
        default = defaults.get('attachments')
    )

    options, args = parser.parse_args()
    wrangler = Wrangler(
        host = options.host,
        port = options.port,
        username = options.username,
        password = options.password,
        database = options.database,
        prefix = options.prefix,
        format = options.format
    )

    has_split = False
    wrangler.select_site(options.site)

    if options.html_fields:
        html_fields = dict(
            [
                [
                    f[0],
                    f[1].split(',')
                ] for f in [
                    s.split(':', 1) for s in options.html_fields.split(' ')
                ]
            ]
        )
    else:
        html_fields = {}

    if path.exists(VARS_FILENAME):
        wrangler.load_vars_file(VARS_FILENAME)

    def save_avatar(url):
        if options.avatar_base:
            new_url = urljoin(options.avatar_base, url)
        else:
            new_url = url

        if options.avatar_path:
            return wrangler.save_download(
                new_url,
                options.avatar_path,
                options.image_domain,
                options.avatar_pattern
            )

        return new_url

    if not options.split_channels:
        wrangler._start_split()
        has_split = True
        wrangler.describe_site()
    else:
        if not path.exists(OUTPUT_DIR):
            makedirs(OUTPUT_DIR)

        print 'Exporting users'
        wrangler._start_split(
            open(
                path.join(
                    OUTPUT_DIR,
                    'index.%s' % options.format
                ),
                'w'
            )
        )

        wrangler.describe_site()
        wrangler._end_split()

        wrangler._start_split(
            open(
                path.join(
                    OUTPUT_DIR,
                    'users.%s' % options.format
                ),
                'w'
            )
        )

        for user in wrangler._raw_select(
            'SELECT m.* FROM %smembers AS m ' \
            'INNER JOIN %schannel_titles AS t ON m.member_id = t.author_id' % (
                options.prefix, options.prefix
            )
        ):
            wrangler.clear_attachments()
            names = user.get('screen_name', '').rsplit(' ', 1)

            if len(names) > 1:
                user['first_name'] = names[0]
                user['last_name'] = names[1]
            elif any(names):
                user['first_name'] = names[0]

            wrangler.describe(user, 'user',
                (
                    'bio',
                    'first_name',
                    'last_name',
                    'occupation',
                    'email'
                ),
                aliases = {
                    'member_id': 'id',
                    'accept_admin_email': 'admin',
                    'avatar_filename': 'avatar'
                },
                transformers = {
                    'last_activity': lambda v: EPOCH + timedelta(
                        seconds = v
                    ),
                    'username': lambda v: v and v.lower().strip().replace(' ', '') or None,
                    'admin': lambda v: v == 'y',
                    'avatar': save_avatar
                },
                end = False
            )

            if options.attachments:
                wrangler.describe_attachments(
                    options.attachments
                )

            wrangler.tidy(1)

        has_split = False
        wrangler._end_split()
        has_split = True

    for channel in wrangler.get_channels():
        if options.split_channels:
            wrangler._start_split(
                open(
                    path.join(
                        OUTPUT_DIR,
                        '%s.%s' % (channel['channel_name'], options.format)
                    ),
                    'w'
                )
            )

            has_split = True
            print 'Exporting %s channel' % channel['channel_name']
        else:
            wrangler.describe(channel, 'channel',
                ('name', 'title', 'description'),
                end = False,
                section_name = 'section',
                aliases = {
                    'name': 'slug',
                    'title': 'name'
                }
            )

        for title in wrangler.get_titles(
            channel['channel_id'],
            status = 'open'
        ):
            wrangler.describe(title, 'title',
                ('title',),
                end = False,
                aliases = {
                    'url_title': 'slug',
                    'entry_id': 'id'
                },
                transformers = {
                    'sticky': lambda v: v == 'y',
                    'author_id': lambda v: (
                        'author',
                        dict(
                            wrangler._prepare(
                                wrangler.get_author(v),
                                'member',
                                (
                                    'username',
                                ),
                                transformers = {
                                    'last_activity': lambda v: EPOCH + timedelta(
                                        seconds = v
                                    ),
                                    'username': lambda v: v and v.lower().strip().replace(' ', '') or None
                                }
                            ),
                            **wrangler._prepare(
                                wrangler._pivot(
                                    'member_fields',
                                    'member_data',
                                    'm',
                                    member_id = v
                                ),
                                'member'
                            )
                        )
                    ),
                    'entry_date': lambda v: (
                        'date',
                        EPOCH + timedelta(seconds = v)
                    )
                },
                section_name = 'item'
            )

            wrangler.clear_attachments()

            for key, value in wrangler._pivot(
                'channel_fields',
                'channel_data',
                channel_id = channel['channel_id'],
                entry_id = title['entry_id']
            ).items():
                if isinstance(value, dict):
                    wrangler.describe(value, 'relationship')
                elif isinstance(value, FileDownload):
                    wrangler._formatter.property(key,
                        wrangler.save_download(value,
                            options.image_path,
                            options.image_domain,
                            options.image_pattern
                        )
                    )
                elif (
                    key.endswith('_content') or \
                    key.endswith('_body') or \
                    key.endswith('_text') or \
                    key in ('content', 'body', 'text')
                ) or key in html_fields.get(channel['channel_name'], []):
                    value = wrangler.parse_for_images(
                        value,
                        options.image_path,
                        options.image_domain,
                        options.image_pattern
                    )

                    wrangler._formatter.property(key,
                        HtmlString(
                            wrangler.vars_replace(value)
                        )
                    )
                else:
                    wrangler._formatter.property(
                        key,
                        wrangler.vars_replace(value)
                    )

            categories = wrangler.get_title_categories(
                title['entry_id']
            )

            if any(categories):
                wrangler._formatter.start_section('categories')
                for category in categories:
                    wrangler._formatter.property('category', category['name'])

                wrangler._formatter.end_section()

            if options.attachments:
                wrangler.describe_attachments(
                    options.attachments
                )

            wrangler.tidy(1)

        if options.split_channels:
            wrangler._end_split()
            has_split = False
        else:
            wrangler.tidy(1)

    if not options.split_channels:
        wrangler._end_split()
        has_split = True

if __name__ == "__main__":
    main()
